apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      serviceAccountName: gateway-sa
      containers:
        - name: gateway
          image: loind/gateway-service:1.0
          ports:
            - containerPort: 8080
