spring:

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/movie
    username: postgres
    password: 123456

#  cloud:
#    vault:
#      uri: ${VAULT_URI:http://localhost:8200}
#      token: ${VAULT_TOKEN:root}
#      kv:
#        enabled: true
#        backend: movie          # KV secrets engine mount path
#        default-context: postgres   # đọc từ secret/movie
#      authentication: TOKEN
#
#  config:
#    import: vault://


  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: CinemaScheduler
            instanceId: AUTO
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            isClustered: true
            tablePrefix: scheduler.QRTZ_
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.pem
  application:
    name: showtime-service

cinema:
  security:
    jwt:
      user-id-claim: sub

  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true
    tags:
      application: showtime-service

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317

  service:
    name: order-service

server:
  port: 8084