input {
  tcp {
    port => 5000
    codec => json
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{service}-logs-%{+YYYY.MM.dd}"
    user => "elastic"
    password => "123456"
  }

  stdout {
    codec => rubydebug
  }
}
