server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: analytics-service-debug
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
    streams:
      application-id: analytics-service
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  application:
    name: analytic-service

  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000

logging:
  level:
    org.apache.kafka.streams: INFO