nameOverride: gateway-service
fullnameOverride: gateway-service

replicaCount: 3

image:
  repository: loind/gateway-service
  tag: "1.0"
  pullPolicy: IfNotPresent

container:
  port: 8080

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: api.local
      paths:
        - path: /
          pathType: ImplementationSpecific

rbac:
  create: true

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 140    # ← chờ 60s sau khi container start mới bắt đầu probe
  periodSeconds: 15          # probe mỗi 15s
  failureThreshold: 3        # fail 3 lần liên tiếp mới kill
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 130    # readiness check sớm hơn liveness
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

startupProbe:               # ← cách tốt hơn cho app chậm khởi động
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  failureThreshold: 30      # cho phép fail 30 lần × periodSeconds 10s = 5 phút để khởi động
  periodSeconds: 10